### ISSUE TITLE
`?.` and `??` tokens

### ISSUE THREAD

**Issue by RblSb** [HaxeCheckstyle/tokentree#218]
Also `??=`.
`final a = true ?.0 : .1;` parsed as safe navigation with compiler error btw

**Comment by AlexHaxe** [comment]
> Also `??=`. 

not sure what you mean, can you give more information?

>`final a = true ?.0 : .1;` parsed as safe navigation with compiler error btw

you are right, seems like Haxe doesn't compile that line either. so it needs to be fixed in Haxe and haxeparser. can you open an issue with Haxe (if you haven't already)?

**Comment by RblSb** [comment]
We can parse `??=` as `Binop(OpAssignOp(OpNullCoal))`, if `??` is `OpNullCoal`, like `+=` is `Binop(OpAssignOp(OpAdd))`.
I don't think `?.0` is a unknown bug, and it's more like parser limitation, so i mean that we can copy this behavior and always parse `?.` as `SafeNav` token (or like that). But we can confirm if this will be resolved or not

**Comment by AlexHaxe** [comment]
tokentree builds on top of haxeparser's lexer. so whatever tokens HaxeLexer produces is what tokentree sees and has to work with.

`??=` already results in `Binop(OpAssignOp(OpNullCoal))` which is consistent with Haxe (see your commit https://github.com/HaxeFoundation/haxe/pull/10428/commits/fc68ea45cc2ee707f351303057892b013425a66d).

?.0 is a parser error in Haxe and tokentree (because HaxeLexer gives a `?.` and `0` instead of `?` and `.0`). I could try to fix the lexer rules in haxeparser so that it would correctly detect that situation and emit correct tokens, but then haxeparser would deviate from Haxe's parser. and I try to keep them both as close as possible.

I might be able to patch tokens in tokentree to act as workaround to detect such a constellation. so formatter and other tools could still function even though the code technically doesn't compile. ultimately formatter would then automatically correct that it so the user doesn't even see an issue pop up.

**Comment by RblSb** [comment]
Ah, i guess vscode just uses outdated haxeparser, i see that you added `QuestionDot` in it. There is nothing to do, except to update deps and some token logic after it, i guess?
